name: CI/CD Pipeline

on:
    pull_request:
        branches: [main]
        types: [closed]

jobs:
    test:
        if: github.event.pull_request.merged == true
        uses: ./.github/workflows/test.yml

    build-and-deploy:
        if: github.event.pull_request.merged == true
        needs: test
        uses: ./.github/workflows/build-and-deploy.yml
